"""acerto de escrita e inclusao de campo

Revision ID: 378625f16e23
Revises: 88729aa48882
Create Date: 2024-11-26 19:20:47.956670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378625f16e23'
down_revision = '88729aa48882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))
        batch_op.drop_column('data_msg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contatos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_msg', sa.DATETIME(), nullable=True))
        batch_op.drop_column('respondido')
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###
